#  menu items
[[main]]
  name = "Our Games"
  weight = 1
  url = "games/"

[[main]]
  name = "Assets Store"
  weight = 2
  url = "https://assetstore.unity.com/publishers/102759"

[[main]]
  name = "The Studio"
  weight = 3
  url = "studio/"

[[main]]
  name = "Services"
  weight = 4
  url = "services/"

[[main]]
  name = "Contact"
  weight = 5
  url = "contact/"
